export const picturesApi = [
    {
        id:1,
        imgurl:"./assets/images/image-11.jpeg"
    },
    {
        id:2,
        imgurl:"./assets/images/image-2.webp"
    },
    {
        id:3,
        imgurl:"./assets/images/image-3.webp"
    },
    {
        id:4,
        imgurl:"./assets/images/image-4.webp"
    },
    {
        id:5,
        imgurl:"./assets/images/image-5.webp"
    },
    {
        id:6,
        imgurl:"./assets/images/image-6.webp"
    },
    {
        id:7,
        imgurl:"./assets/images/image-7.webp"
    },
    {
        id:8,
        imgurl:"./assets/images/image-8.webp"
    },
    {
        id:9,
        imgurl:"./assets/images/image-9.webp"
    },
]