export const picturesApi = [
    {
        id:1,
        order:0,
        imgurl:"./assets/images/image-11.jpeg",
        checkbox:false
    },
    {
        id:2,
        order:1,
        imgurl:"./assets/images/image-2.webp",
        checkbox:false
    },
    {
        id:3,
        order:2,
        imgurl:"./assets/images/image-3.webp",
        checkbox:false
    },
    {
        id:4,
        order:3,
        imgurl:"./assets/images/image-4.webp",
        checkbox:false
    },
    {
        id:5,
        order:4,
        imgurl:"./assets/images/image-5.webp",
        checkbox:false
    },
    {
        id:6,
        order:5,
        imgurl:"./assets/images/image-6.webp",
        checkbox:false
    },
    {
        id:7,
        order:6,
        imgurl:"./assets/images/image-7.webp",
        checkbox:false
    },
    {
        id:8,
        order:7,
        imgurl:"./assets/images/image-8.webp",
        checkbox:false
    },
    {
        id:9,
        order:8,
        imgurl:"./assets/images/image-9.webp",
        checkbox:false
    },
]